CC = gcc
C_FLAGS = -Wall -lutil 
INCLUDE = -I../../include/
OBJ = ../util/util.o
SOURCE = hpsys.c 
BIN = ../../bin/hpsys.bin

all: $(OBJ)
	$(CC) $(C_FLAGS) $(INCLUDE) $(LIB) $(SOURCE) $(OBJ) -o $(BIN)

